version: '3.8'

services:
  vite-react-app:
    image: ardfordev/vite-react-app:${IMAGE_TAG}
    container_name: vite-react-app
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge