node {
    def app

    // Setup Docker container
    docker.image('node:iron-slim').inside('-p 3000:3000') {
        withEnv(['CI=true', 'HOST=0.0.0.0', 'PORT=3000']) {
            try {
                stage('Setup') {
                    // Add execute permissions to scripts
                    sh 'chmod +x jenkins/scripts/test.sh'
                    sh 'chmod +x jenkins/scripts/deliver.sh'
                    sh 'chmod +x jenkins/scripts/kill.sh'
                }

                stage('Install') {
                    sh 'npm install'
                }

                stage('Type Check & Build') {
                    sh 'npm run build'
                }

                stage('Lint') {
                    sh 'npm run lint'
                }

                stage('Test') {
                    sh 'sh ./jenkins/scripts/test.sh'
                }

                stage('Preview') {
                    timeout(time: 3, unit: 'MINUTES') {
                        sh 'npm run preview -- --host 0.0.0.0 --port 3000 --strictPort'
                    }
                }

                stage('Deliver') {
                    sh 'sh ./jenkins/scripts/deliver.sh'
                    input message: 'Finished using the website? (Click "Proceed" to continue)'
                    sh 'sh ./jenkins/scripts/kill.sh'
                }
            } catch (e) {
                currentBuild.result = 'FAILED'
                throw e
            }
        }
    }
}